name: eco-finance-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - statsmodels
  - openpyxl
  - scipy
  - seaborn
  - pip
  - pip:
    - arch